version: '3'
services:
  task1:
#    build: ./task1
    image: niatomi/test-tasks_task1:latest
    container_name: task1
    networks:
      - spring
    ports:
      - 8080:8080

  task2:
#    build: ./task2
    image: niatomi/test-tasks_task2:latest
    container_name: task2
    environment:
      - WSDL_HOST=task1
    depends_on:
      - task1
    networks:
      - spring
    ports:
      - 8081:8081

networks:
  spring:
    driver: bridge